### ISSUE TITLE
Correcciones en UX

### ISSUE THREAD

**Issue by nosoyilse** [nosoyilse/prinket#32]
Cuando una agencia hace un pedido lo que dice "recuerda dar un precio especial" se ve super chiquito  y debería de tener más enfoque por que la gente ni lo ve.

Muchos botones de hacer propuestas están cortados.

Checa la imagen.
![prinket](https://cloud.githubusercontent.com/assets/5297096/10201643/ad3e0d64-6772-11e5-9fab-5f1b45de6b33.png)

**Comment by elujambio** [comment]
Arreglado!
