### ISSUE TITLE
Forma y show de propuesta deben de ser iguales

### ISSUE THREAD

**Issue by nosoyilse** [nosoyilse/prinket#36]
Cuando vas a hacer una propuesta en la forma del pedido todo sale junto, cuando ya la haces sale separado, creo que es más claro si queda separado y todo con el mismo estilo.
![prinket3](https://cloud.githubusercontent.com/assets/5297096/10203094/bc214f4c-6779-11e5-9447-0cdd121ca730.png)
![prinket4](https://cloud.githubusercontent.com/assets/5297096/10203096/be4ecc7c-6779-11e5-8033-45ecd98b3635.png)

**Comment by elujambio** [comment]
Fixed. :3
