### ISSUE TITLE
Accepted proposal request

### ISSUE THREAD

**Issue by nosoyilse** [nosoyilse/prinket#45]
When the user accepts a proposal the link looks weird in: http://localhost:3000/requisitions/1
I logged in with rare pepe user

![accept](https://cloud.githubusercontent.com/assets/5297096/10296725/120d7136-6b91-11e5-852c-6c8e7a7ebed2.png)

**Comment by elujambio** [comment]
Fixed in branch 38-incomplete-buttons, to be merged to user-interface, and master.
